DROP TABLE IF EXISTS PARKING;

CREATE TABLE PARKING(
PARKING_NAME VARCHAR2(1000),
PARKING_LAT NUMBER,
PARKING_LON NUMBER,
PARKING_ADDRESS VARCHAR2(1000),
PARKING_CALL VARCHAR2(100),
PARKING_FREE VARCHAR2(10),
PARKING_PLANE INTEGER,
PARKING_MORE INTEGER,
PARKING_PLANE_TIME INTEGER,
PARKING_MORE_TIME INTEGER,
PARKING_DMAX INTEGER,
PARKING_BUS_PLANE INTEGER,
PARKING_BUS_MORE INTEGER);