CREATE INDEX INEDX_HOME_ADDRESS ON HOME(HOME_ADDRESS);
CREATE MATERIALIZED VIEW HOME_AI_MV
REFRESH COMPLETE ON DEMAND
AS
SELECT
    h.HOME_ADDRESS, h.HOME_LAT, h.HOME_LON, h.HOME_NAME, h.HOME_KIND,
    h.HOME_COUNT, h.HOME_CO, h.HOME_PARKING, h.HOME_IMG, h.HOME_NO,
    h.HOME_MYAREA, h.HOME_WEAREA, h.HOME_DEP, h.HOME_MOTH_PAI,
    h.HOME_CHANGE_DEP, h.HOME_RECR, al.ADDRESS, al.PARK_DIST,
     al.HOS_DIST,  al.SUB_DIST,
    al.BUS_DIST,  al.PARKING_DIST,  al.LOW_DIST,
     al.MID_DIST, al.HI_DIST
FROM HOME h
LEFT JOIN AI_LEARN al ON h.HOME_ADDRESS = al.ADDRESS;

CREATE VIEW HOME_AI_VIEW AS
SELECT
    h.HOME_ADDRESS,
    h.HOME_LAT,
    h.HOME_LON,
    h.HOME_NAME,
    h.HOME_KIND,
    h.HOME_COUNT,
    h.HOME_CO,
    h.HOME_PARKING,
    h.HOME_IMG,
    h.HOME_NO,
    h.HOME_MYAREA,
    h.HOME_WEAREA,
    h.HOME_DEP,
    h.HOME_MOTH_PAI,
    h.HOME_CHANGE_DEP,
    h.HOME_RECR,
    al.ADDRESS,
    al.PARK_DIST,
    al.HOS_DIST,
    al.SUB_DIST,
    al.BUS_DIST,
    al.PARKING_DIST,
    al.LOW_DIST,
    al.MID_DIST,
    al.HI_DIST
FROM HOME h
LEFT JOIN AI_LEARN al ON h.HOME_ADDRESS = al.ADDRESS;